'use client';
import { useEffect, useState } from 'react';
import { accountRequest } from '@/lib/account-client';
export default function Stage5Settings() {
  const [enabled,setEnabled]=useState(false),[notice,setNotice]=useState(''),[email,setEmail]=useState(false),[whatsapp,setWhatsapp]=useState(false),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[orderNumber,setOrderNumber]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{ void accountRequest('communication-preferences').then(r=>{setEnabled(Boolean(r.enabled));setNotice(r.notice||'');setEmail(Boolean(r.preferences?.email));setWhatsapp(Boolean(r.preferences?.whatsapp));}).catch(()=>setError('Tercihler yüklenemedi.')); },[]);
  async function run(fn:()=>Promise<{message?:string}>) { setBusy(true);setError('');setMessage('');try{const r=await fn();setMessage(r.message||'İşlem tamamlandı.');}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);} }
  return <div className="space-y-6"><section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">İletişim tercihleri</h2><p className="text-sm text-slate-600">Sipariş ve hesap işlemleriyle ilgili zorunlu bildirimler bu tercihlerden bağımsızdır.</p>{enabled?<><p className="whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-sm">{notice}</p><label className="flex gap-3"><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/>E-posta pazarlama iletileri</label><label className="flex gap-3"><input type="checkbox" checked={whatsapp} onChange={e=>setWhatsapp(e.target.checked)}/>WhatsApp pazarlama iletileri</label><button disabled={busy} onClick={()=>void run(()=>accountRequest('communication-preferences-save',{email,whatsapp}))} className="min-h-11 rounded-xl bg-violet-700 px-4 text-white">Tercihleri kaydet</button></>:<p className="rounded-lg bg-amber-50 p-3 text-sm">Onaylı bilgilendirme metni yapılandırılmadığı için pazarlama izni toplama kapalıdır.</p>}</section>
  <section className="space-y-4 rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Eski misafir siparişini hesabıma bağla</h2><p className="text-sm text-slate-600">Doğrulama yalnızca sipariş kaydındaki e-posta adresine gönderilir. Sipariş numarası tek başına sahiplik kanıtı değildir.</p><input className="min-h-11 w-full rounded-xl border p-3" value={orderNumber} onChange={e=>setOrderNumber(e.target.value)} placeholder="Sipariş numarası"/><button disabled={busy||!orderNumber.trim()} onClick={()=>void run(()=>accountRequest('claim-guest-order',{orderNumber}))} className="min-h-11 rounded-xl border px-4">Doğrulama iste</button></section>
  <section className="space-y-4 rounded-2xl border border-red-200 bg-white p-5"><h2 className="text-xl font-bold text-red-800">Hesap silme başvurusu</h2><p className="text-sm text-slate-600">Yeniden şifre doğrulaması gerekir. Başvuru anında veri silinmez; siparişler, ödeme belirsizliği ve saklama engelleri ayrıca incelenir.</p><input className="min-h-11 w-full rounded-xl border p-3" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mevcut şifreniz"/><textarea className="w-full rounded-xl border p-3" rows={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} placeholder="İsteğe bağlı açıklama"/><button disabled={busy||!password} onClick={()=>void run(()=>accountRequest('account-delete-request',{password,reason}))} className="min-h-11 rounded-xl bg-red-700 px-4 text-white">Silme başvurusu oluştur ve oturumu kapat</button></section>
  {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}{message&&<p role="status" className="rounded-lg bg-emerald-50 p-3">{message}</p>}</div>;
}
