'use client';
import { useEffect, useState } from 'react';
import { accountRequest } from '@/lib/account-client';
import { Notice, PageHeading, fieldClass, primaryButtonClass, secondaryButtonClass } from '@/components/account/ui';
export default function Stage5Settings() {
  const [enabled,setEnabled]=useState(false),[notice,setNotice]=useState(''),[email,setEmail]=useState(false),[whatsapp,setWhatsapp]=useState(false),[password,setPassword]=useState(''),[reason,setReason]=useState(''),[orderNumber,setOrderNumber]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{ void accountRequest('communication-preferences').then(r=>{setEnabled(Boolean(r.enabled));setNotice(r.notice||'');setEmail(Boolean(r.preferences?.email));setWhatsapp(Boolean(r.preferences?.whatsapp));}).catch(()=>setError('Tercihler yüklenemedi.')); },[]);
  async function run(fn:()=>Promise<{message?:string}>) { setBusy(true);setError('');setMessage('');try{const r=await fn();setMessage(r.message||'İşlem tamamlandı.');}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.');}finally{setBusy(false);} }
  return <div className="space-y-5"><PageHeading eyebrow="Gizlilik ve iletişim" title="Tercihler ve veri" description="Pazarlama tercihlerinizi, eski sipariş bağlantılarını ve hesap başvurularını yönetin." /><section className="account-surface account-section space-y-4"><h3 className="account-section-title">İletişim tercihleri</h3><p className="text-sm text-slate-600">Sipariş ve hesap işlemleriyle ilgili zorunlu bildirimler bu tercihlerden bağımsızdır.</p>{enabled?<><p className="whitespace-pre-wrap rounded-xl bg-slate-50 p-3 text-sm">{notice}</p><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={email} onChange={e=>setEmail(e.target.checked)}/>E-posta pazarlama iletileri</label><label className="flex min-h-11 items-center gap-3"><input type="checkbox" checked={whatsapp} onChange={e=>setWhatsapp(e.target.checked)}/>WhatsApp pazarlama iletileri</label><button disabled={busy} onClick={()=>void run(()=>accountRequest('communication-preferences-save',{email,whatsapp}))} className={primaryButtonClass}>Tercihleri kaydet</button></>:<Notice kind="warning">Onaylı bilgilendirme metni yapılandırılmadığı için pazarlama izni toplama kapalıdır.</Notice>}</section>
  <section className="account-surface account-section space-y-4"><h3 className="account-section-title">Misafir siparişini hesabıma bağla</h3><p className="text-sm text-slate-600">Doğrulama yalnızca sipariş kaydındaki e-posta adresine gönderilir. Sipariş numarası tek başına sahiplik kanıtı değildir.</p><label className="block text-sm font-semibold">Sipariş numarası<input className={fieldClass} value={orderNumber} onChange={e=>setOrderNumber(e.target.value)} /></label><button disabled={busy||!orderNumber.trim()} onClick={()=>void run(()=>accountRequest('claim-guest-order',{orderNumber}))} className={secondaryButtonClass}>Doğrulama iste</button></section>
  <section className="account-surface account-section space-y-4 border-red-200"><h3 className="account-section-title text-red-800">Hesap silme başvurusu</h3><p className="text-sm text-slate-600">Yeniden şifre doğrulaması gerekir. Başvuru anında veri silinmez; siparişler, ödeme belirsizliği ve saklama engelleri ayrıca incelenir.</p><label className="block text-sm font-semibold">Mevcut şifre<input className={fieldClass} type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} /></label><label className="block text-sm font-semibold">Açıklama (isteğe bağlı)<textarea className={fieldClass} rows={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)} /></label><button disabled={busy||!password} onClick={()=>void run(()=>accountRequest('account-delete-request',{password,reason}))} className="account-button bg-red-700 text-white">Silme başvurusu oluştur ve oturumu kapat</button></section>
  {error&&<Notice kind="error">{error}</Notice>}{message&&<Notice kind="success">{message}</Notice>}</div>;
}
