import Link from 'next/link';
import { accountBackend } from '@/lib/server/account';
import Image from 'next/image';
import OfferActions from '@/components/figurine/OfferActions';
import { PageHeading, StatusBadge } from '@/components/account/ui';

type PersonDetail = { id: string; kind: 'person' | 'pet'; description: string; outfit?: string; hair?: string; pose?: string; accessories?: string; appearance?: string; distinctiveFeatures?: string };
type FigurineRequest = { requestId: string; requestNumber: string; status: string; createdAt: string; package: { title: string } | null; message: string; details: { style: string; characters: number; pets: number; people: PersonDetail[]; plinthText?: string; note?: string; contactPreference: string; phone?: string } };
type FigurineOffer = { id: string; version: number; state: string; scope: { characters: number; pets: number; colorChoice: string; designDescription: string; includedParts: string[]; sizeDescription?: string; standIncluded?: boolean | null; boxIncluded?: boolean | null; productionDeliveryNote?: string }; amountMinor: number; taxMinor: number; shippingMinor: number; totalMinor: number; currency: string; taxShippingDisclosure: string; customerNote: string; validUntil?: string | null; acceptedAt?: string | null; approvalInvalidatedAt?: string | null };
type ExistingOrder = { id: string; orderNumber: string; paymentState: string; fulfillmentState: string | null; shippingCarrier: string | null; trackingNumber: string | null; trackingUrl: string | null; customerNote: string; grandTotal: number; currency: string; paymentAvailable: boolean } | null;

export const dynamic = 'force-dynamic';
export const metadata = { robots: { index: false, follow: false }, title: 'Figür Talebi' };

export default async function FigurineRequestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await accountBackend('figurine-request', { id });
  if (result.status !== 200) return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Talep bulunamadı</h2><p className="mt-2 text-slate-600">Talep hesabınızda bulunamadı veya şu anda açılamıyor.</p><Link className="mt-4 inline-block text-purple-700" href="/hesap/figur-talepleri">Taleplerime dön</Link></section>;
  const { request, photos, offers = [], order = null, paymentsEnabled = false } = result.body as { request: FigurineRequest; photos: { id: string }[]; offers?: FigurineOffer[]; order?: ExistingOrder; paymentsEnabled?: boolean };
  const details = request.details || {};
  const nextStep = offers.some(o => o.state === 'offered') ? 'Teklifinizi inceleyip onaylayın veya değişiklik isteyin.' : order ? 'Sipariş durumunu aşağıdan takip edin.' : 'Talebiniz ekibimiz tarafından inceleniyor.';
  return <article className="space-y-5">
    <Link className="inline-flex min-h-11 items-center text-sm font-bold text-purple-700" href="/hesap/figur-talepleri">← Figür taleplerime dön</Link>
    <PageHeading eyebrow="Figür talebi" title={request.requestNumber} description={new Date(request.createdAt).toLocaleString('tr-TR')} action={<StatusBadge tone="purple">{request.status}</StatusBadge>} />
    <section className="account-surface"><div className="account-section grid gap-5 sm:grid-cols-3"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Paket</p><p className="mt-1 font-bold">{request.package?.title || 'Özel talep'}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">Tercih</p><p className="mt-1 font-bold">{details.style === 'color' ? 'Renkli' : 'Beyaz / tek renk'}</p></div><div><p className="text-xs font-bold uppercase tracking-wide text-slate-500">İçerik</p><p className="mt-1 font-bold">{details.characters} kişi · {details.pets} pet</p></div></div><div className="account-section bg-purple-50/60"><p className="text-xs font-bold uppercase tracking-wide text-purple-700">Sonraki adım</p><p className="mt-1 font-semibold text-slate-800">{nextStep}</p></div></section>
    <section className="account-surface"><div className="account-section"><h3 className="account-section-title">Kişi ve pet ayrıntıları</h3></div><div className="grid gap-px bg-slate-200 sm:grid-cols-2">{(details.people || []).map((person, index) => <div key={person.id || index} className="bg-white p-5"><h4 className="font-bold">{person.kind === 'person' ? 'Kişi' : 'Pet'} {index + 1}</h4><p className="mt-2 whitespace-pre-wrap text-sm leading-6">{person.description || 'Ek açıklama yok.'}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{person.kind === 'person' ? [person.outfit && `Kıyafet: ${person.outfit}`, person.hair && `Saç: ${person.hair}`, person.pose && `Poz: ${person.pose}`, person.accessories && `Aksesuar: ${person.accessories}`].filter(Boolean).join(' · ') || 'Ek tercih yok.' : [person.appearance && `Görünüm: ${person.appearance}`, person.distinctiveFeatures && `Belirgin özellikler: ${person.distinctiveFeatures}`, person.pose && `Poz: ${person.pose}`].filter(Boolean).join(' · ') || 'Ek tercih yok.'}</p></div>)}</div></section>
    <section className="account-surface account-section"><h3 className="account-section-title">Diğer tercihler</h3><div className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><p><span className="block font-semibold text-slate-500">Kaide yazısı</span>{details.plinthText || 'Belirtilmedi'}</p><p><span className="block font-semibold text-slate-500">İletişim tercihi</span>{details.contactPreference === 'whatsapp' ? `WhatsApp · ${details.phone}` : 'E-posta'}</p>{details.note && <p className="whitespace-pre-wrap sm:col-span-2"><span className="block font-semibold text-slate-500">Ek not</span>{details.note}</p>}</div><p className="mt-4 border-t border-slate-100 pt-4 text-sm text-slate-600">{request.message}</p></section>
    {photos.length > 0 && <section className="account-surface account-section"><h3 className="account-section-title">Referans fotoğrafları</h3><p className="mt-1 text-sm text-slate-500">Büyütmek için fotoğrafa dokunun. Fotoğraflar yalnız hesabınız üzerinden açılır.</p><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{photos.map(photo => { const src = `/api/account/figurine-photo?id=${encodeURIComponent(request.requestId)}&asset=${encodeURIComponent(photo.id)}`; return <a key={photo.id} href={src} target="_blank" rel="noreferrer" className="group flex aspect-square items-center justify-center overflow-hidden rounded-xl border border-slate-200 bg-slate-50 focus:outline-none focus:ring-2 focus:ring-purple-400"><Image unoptimized width={480} height={480} src={src} alt="Özel referans fotoğrafını büyüt" className="h-full w-full object-contain transition group-hover:scale-[1.02]" referrerPolicy="no-referrer" /></a>; })}</div></section>}
    <OfferActions requestId={request.requestId} offers={offers} existingOrder={order} paymentsEnabled={paymentsEnabled} />
    {order && <section className="account-surface account-section"><h3 className="account-section-title">Sipariş takibi</h3><div className="mt-3 space-y-1 text-sm"><p>Ödeme: {order.paymentState === 'paid' ? 'Ödendi' : order.paymentState === 'unknown' ? 'Sonuç doğrulanıyor' : 'Ödeme bekleniyor'}</p><p>Operasyon: {order.fulfillmentState || 'Henüz güncellenmedi'}</p>{order.shippingCarrier && <p>Kargo firması: {order.shippingCarrier}</p>}{order.trackingNumber && <p>Takip numarası: {order.trackingNumber}</p>}{order.trackingUrl && <a href={order.trackingUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center font-bold text-violet-700 underline">Kargo takibi</a>}{order.customerNote && <p className="mt-2 whitespace-pre-wrap">{order.customerNote}</p>}</div></section>}
  </article>;
}
