import Link from 'next/link';
import { accountBackend } from '@/lib/server/account';
import Image from 'next/image';
import OfferActions from '@/components/figurine/OfferActions';

type PersonDetail = { id: string; kind: 'person' | 'pet'; description: string; outfit?: string; hair?: string; pose?: string; accessories?: string; appearance?: string; distinctiveFeatures?: string };
type FigurineRequest = { requestId: string; requestNumber: string; status: string; createdAt: string; package: { title: string } | null; message: string; details: { style: string; characters: number; pets: number; people: PersonDetail[]; plinthText?: string; note?: string; contactPreference: string; phone?: string } };
type FigurineOffer = { id: string; version: number; state: string; scope: { characters: number; pets: number; colorChoice: string; designDescription: string; includedParts: string[]; sizeDescription?: string; standIncluded?: boolean | null; boxIncluded?: boolean | null; productionDeliveryNote?: string }; amountMinor: number; taxMinor: number; shippingMinor: number; totalMinor: number; currency: string; taxShippingDisclosure: string; customerNote: string; validUntil?: string | null; acceptedAt?: string | null; approvalInvalidatedAt?: string | null };
type ExistingOrder = { id: string; orderNumber: string; paymentState: string; fulfillmentState: string | null; shippingCarrier: string | null; trackingNumber: string | null; trackingUrl: string | null; customerNote: string; grandTotal: number; currency: string; paymentAvailable: boolean } | null;

export const dynamic = 'force-dynamic';
export const metadata = { robots: { index: false, follow: false }, title: 'Figür Talebi' };

export default async function FigurineRequestDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const result = await accountBackend('figurine-request', { id });
  if (result.status !== 200) return <section className="rounded-2xl border border-slate-200 bg-white p-6"><h2 className="text-xl font-bold">Talep bulunamadı</h2><p className="mt-2 text-slate-600">Talep hesabınızda bulunamadı veya şu anda açılamıyor.</p><Link className="mt-4 inline-block text-purple-700" href="/hesap/figur-talepleri">Taleplerime dön</Link></section>;
  const { request, photos, offers = [], order = null, paymentsEnabled = false } = result.body as { request: FigurineRequest; photos: { id: string }[]; offers?: FigurineOffer[]; order?: ExistingOrder; paymentsEnabled?: boolean };
  const details = request.details || {};
  return <article className="space-y-5 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7">
    <Link className="text-sm font-semibold text-purple-700" href="/hesap/figur-talepleri">← Figür taleplerim</Link>
    <div><p className="text-sm font-bold text-purple-700">{request.status}</p><h2 className="mt-1 text-2xl font-black">{request.requestNumber}</h2><p className="mt-1 text-sm text-slate-500">{new Date(request.createdAt).toLocaleString('tr-TR')}</p></div>
    <section><h3 className="font-bold">Paket ve tercihler</h3><p className="mt-2">{request.package?.title || 'Özel talep'} · {details.style === 'color' ? 'Renkli' : 'Beyaz / tek renk'}</p><p className="mt-1 text-sm text-slate-600">{details.characters} karakter · {details.pets} pet</p><p className="mt-2 text-sm text-slate-600">Başlangıç fiyatı kesin teklif veya sipariş tutarı değildir.</p></section>
    <section className="space-y-4"><h3 className="font-bold">Kişi ve pet ayrıntıları</h3>{(details.people || []).map((person, index) => <div key={person.id || index} className="rounded-xl bg-slate-50 p-4"><h4 className="font-semibold">{person.kind === 'person' ? 'Kişi' : 'Pet'} {index + 1}</h4><p className="mt-1 whitespace-pre-wrap text-sm">{person.description || 'Ek açıklama yok.'}</p><p className="mt-2 whitespace-pre-wrap text-sm text-slate-600">{person.kind === 'person' ? [person.outfit && `Kıyafet: ${person.outfit}`, person.hair && `Saç: ${person.hair}`, person.pose && `Poz: ${person.pose}`, person.accessories && `Aksesuar: ${person.accessories}`].filter(Boolean).join(' · ') || 'Ek tercih yok.' : [person.appearance && `Görünüm: ${person.appearance}`, person.distinctiveFeatures && `Belirgin özellikler: ${person.distinctiveFeatures}`, person.pose && `Poz: ${person.pose}`].filter(Boolean).join(' · ') || 'Ek tercih yok.'}</p></div>)}</section>
    <section><h3 className="font-bold">Diğer tercihler</h3><p className="mt-2 text-sm">Kaide yazısı: {details.plinthText || 'Belirtilmedi'}</p><p className="mt-1 whitespace-pre-wrap text-sm">Ek not: {details.note || 'Yok'}</p><p className="mt-2 text-sm">İletişim tercihi: {details.contactPreference === 'whatsapp' ? `WhatsApp · ${details.phone}` : 'E-posta'}</p><p className="mt-3 text-sm text-slate-600">{request.message}</p></section>
    {photos.length > 0 && <section><h3 className="font-bold">Referans fotoğrafları</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{photos.map(photo => <Image key={photo.id} unoptimized width={480} height={480} src={`/api/account/figurine-photo?id=${encodeURIComponent(request.requestId)}&asset=${encodeURIComponent(photo.id)}`} alt="Özel referans fotoğrafı" className="aspect-square w-full rounded-xl bg-slate-100 object-cover" referrerPolicy="no-referrer" />)}</div></section>}
    <OfferActions requestId={request.requestId} offers={offers} existingOrder={order} paymentsEnabled={paymentsEnabled} />
    {order && <section className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold">Sipariş takibi</h3><p className="mt-2">Ödeme: {order.paymentState === 'paid' ? 'Ödendi' : order.paymentState === 'unknown' ? 'Sonuç doğrulanıyor' : 'Ödeme bekliyor'}</p><p>Hazırlık / teslimat: {order.fulfillmentState || 'Henüz güncellenmedi'}</p>{order.shippingCarrier && <p>Kargo firması: {order.shippingCarrier}</p>}{order.trackingNumber && <p>Takip numarası: {order.trackingNumber}</p>}{order.trackingUrl && <a href={order.trackingUrl} target="_blank" rel="noopener noreferrer" className="text-violet-700 underline">Kargo takibi</a>}{order.customerNote && <p className="mt-2 whitespace-pre-wrap">{order.customerNote}</p>}</section>}
  </article>;
}
